image: gitpod/workspace-full
tasks:
  - before: export VUE_APP_CUSTOM_URL=$(gp url)
    init: export VUE_APP_CUSTOM_URL=$(gp url) make
    command: rm -rf starport
ports:
  - port: 1317
  - port: 26657
  - port: 8080
